### ISSUE TITLE
Update GraphQL Validation Action to fix DependaBot PRs

### ISSUE THREAD

**Issue by JSneak** [dictyBase/dicty-graphql-schema#35]
Issues regarding dicty-graphql-schema/pulls
1. Need to delete yarn.lock and run yarn init
    1. https://github.com/yarnpkg/berry/issues/3416
2. Looks like an issue with the bot itself
    1. https://github.com/dependabot/dependabot-core/issues/1297

**Comment by ayaanqui** [comment]
@JSneak Is this issue related to running `yarn generate` and `yarn compile` which also fails. Here's what I receive when I run the commands:
```
✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./types/index.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →         at /.../dicty-graphql-schema/src/queries/listOfPublications.gra…

 Found 1 error

  ✖ ./types/index.ts
    AggregateError: 
        GraphQLDocumentError: Unknown argument "limit" on field "Query.publication".
            at /.../dicty-graphql-schema/src/queries/listOfPublications.graphql:2
:15
...
```

**Comment by JSneak** [comment]
@ayaanqui No I need to revert the the last commit as it had some unforeseen errors. I'll do that right now.

https://github.com/dictyBase/dicty-graphql-schema/commit/f3bcbdf7f5ea8b0682ef480b15130159abcf8183
