### ISSUE TITLE
Update GeneQuery to return references

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/dicty-graphql-schema#89]
PR https://github.com/dictyBase/genomepage/pull/864 implements a references tab, which will require a new field (perhaps something like `allReferences`?) to be added to the existing [src/queries/gene.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/2c2be58f4bc10ffbf4c18c7ed73f1f80f62995b8/src/queries/gene.graphql) file.

Here's a suggestion to how the query type could look like:
```graphql
allReferences(gene: $gene) {
    id
    name
    strains {
      id
      label
      phenotypes {
        publication {
          id
          title
          journal
          pages
          volume
          pub_date
          authors {
            last_name
            rank
          }
        }
      }
    }
  }
```

**Comment by cybersiddhu** [comment]
So, how are you querying the references anyway ?

**Comment by ayaanqui** [comment]
Isn't a reference just a `Publication` for a given `Phenotype`? Or am I missing something?

**Comment by ayaanqui** [comment]
At the moment I'm not making any queries since the schema isn't done, so once it's ready I can then create the mock data and start implementing it. Right now I'm mostly refactoring so we don't have all those nested directories
